name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.8, 3.12]

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: poetry check
        run: poetry check
      - name: poetry install
        run: poetry install
      - name: django-admin check
        run: python run python testmanage.py check
      - name: django-admin test
        run: python run python testmanage.py test
